apiVersion: apps/v1
kind: Deployment
metadata:
  name: external-deployment
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: external
        image: gcr.io/roidtc-user201/external-image:v1.0.0
        ports:
        - containerPort: 8080
